export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  SIGNUP_DOCTOR: '/signup/doctor',
  SIGNUP_HOSPITAL: '/signup/hospital',
  CHANGE_PASSWORD: '/change-password',
  ABOUT: '/about',
  SERVICES: '/services',
  CONTACT: '/contact',
  FIND_DOCTORS: '/find-doctors',
  FIND_HOSPITALS: '/find-hospitals',
  PUBLIC_HOSPITAL: '/hospitals/:id',
  NOTIFICATIONS: '/notifications',
  EMERGENCY: '/emergency',
  BLOOD_BANK: '/blood-bank',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  DASHBOARD: '/dashboard',
  
  PATIENT: {
    DASHBOARD: '/patient/dashboard',
    BOOKING_HUB: '/patient/book-appointment',
    MY_BOOKINGS: '/patient/appointments',
    PRESCRIPTIONS: '/patient/prescriptions',
    PROFILE: '/patient/profile',
    CONSULTATION: '/patient/consultation/doctors',
    ROOM: '/patient/consultation/room/:sessionId',
    REVIEWS: '/patient/reviews/:id',
    TOKEN_TRACKER: '/patient/tracker',
  },
  
  HOSPITAL: {
    DASHBOARD: '/hospital/dashboard',
    DOCTORS: '/hospital/doctors',
    APPOINTMENTS: '/hospital/appointments',
    OFFLINE_BOOKING: '/hospital/offline-booking',
    PROFILE: '/hospital/profile',
    FACILITIES: '/hospital/facilities',
  },
  
  DOCTOR: {
    DASHBOARD: '/doctor/dashboard',
    APPOINTMENTS: '/doctor/appointments',
    AVAILABILITY: '/doctor/availability',
    PRESCRIPTIONS: '/doctor/prescriptions',
    PROFILE: '/doctor/profile',
    CONSULTATION: '/doctor/consultation/sessions',
    ROOM: '/doctor/consultation/room/:sessionId',
  },
  
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    HOSPITALS: '/admin/hospitals',
    DOCTORS: '/admin/doctors',
    REGISTRATIONS: '/admin/registrations',
    REVENUE: '/admin/revenue',
    PROFILE: '/admin/profile',
  },
};
